services:
    db:
        image: postgres:15
        environment:
            POSTGRES_USER: taskuser
            POSTGRES_PASSWORD: taskpass
            POSTGRES_DB: taskdb
        volumes:
            - db_data:/var/lib/postgresql/data
        networks:
            - task-manager
    
    frontend:
        image: frontend-img
        ports:
            - "8081:80"
        networks:
            - task-manager
    
    backend:
        image: backend-img
        ports:
            - "8000:8000"
        networks: 
            - task-manager

networks: 
  task-manager:
    driver: bridge

volumes:
    db_data: 

