services:
    db:
        image: postgres:15
        environment:
            POSTGRES_USER: taskuser
            POSTGRES_PASSWORD: taskpass
            POSTGRES_DB: taskdb
        volumes:
            - db_data:/var/lib/postgresql/data
        networks:
            - task-manager
    
    frontend:
        build: ../frontend
        networks:
            - task-manager
    
    backend:
        build : ./backend
        networks: 
            - task-manager

networks: 
  task-manager:
    driver: bridge

volumes:
    db_data: 

