apiVersion: apps/v1
kind: Deployment 
metadata:
  name: frontend-deployment
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
        - name: gitlab-registry-secret
      containers:
        - name: frontend-container  
          image: registry.gitlab.com/fineshift/users/sanket-jadhav/task-manager-project/frontend 
          imagePullPolicy: Always
          ports:
            - containerPort: 80
